# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

modelscope_hidden = collect_submodules('modelscope')

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('iic', 'iic'),
        (r'.venv\Lib\site-packages\modelscope\utils\ast_index_file.py', 'modelscope/utils'),
        (r'app\services\agent_prompt.md', 'app/services'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'pandas',
        'openpyxl',
        'redis',
        'transformers',
        'torch',
        'app',
        'app.main',
        'app.api',
        'app.api.routes',
        'app.core',
        'app.core.config',
        'app.schemas',
        'app.schemas.address',
        'app.schemas.address_fill',
        'app.services',
        'app.services.db',
        'app.services.split_service',
        'app.services.address_fill_service',
        'app.services.address_fill_agent',
        'app.services.model_service',
        'app.services.progress_ws',
        'app.services.task_control',
        'app.services.environment_config',
        'app.services.model_config',
        'app.services.redis_store',
        'app.services.validation_rule_service',
        'app.services.job_store',
        'app.services.document_parsers',
        'app.services.constants',
        'app.services.bing_search',
        'mgeo_geographic_elements_tagging_chinese_base',
        'mgeo_geographic_where_what_cut_chinese_base',
    ] + modelscope_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'nvidia',
        'cuda',
        'cudnn',
        'triton',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AddressSplitTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
